version: '3.8'

services:
  postgress:
    container_name: api_cursos_postgress
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_api_cursos
      POSTGRES_DB: api_cursos
    ports:
      - "5433:5432"