version: '3.8'

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgress:
    container_name: api_cursos_postgress
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_api_cursos
      POSTGRES_DB: api_cursos
    ports:
      - "5432:5432"
  prometheus:
    container_name: api_cursos_prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    ports:
      - 9090:9090
  grafana:
    container_name: api_cursos_grafana
    image: grafana/grafana:latest
    networks:
      - gv-network
    ports:
      - 3000:3000